export enum ServerEvents {
  CLIENT_JOIN = "CLIENT_JOIN",
  CLIENT_LEAVE = "CLIENT_LEAVE",
  GAME_START_TIME = "GAME_START_TIME",
  ON_JOIN = "ON_JOIN",
  ON_LEAVE = "ON_LEAVE",
  GAME_START = "GAME_START",
  PLAYER_POSITION = "PLAYER_POSITION",
  PLAYER_ANIMATION = "PLAYER_ANIMATION",
  PLAYER_DATA_UPDATE = "PLAYER_DATA_UPDATE",
  PLAYER_WINNER = "PLAYER_WINNER",
  NEW_ROUND_START = "NEW_ROUND_START",



}
export enum ClientEvents {
  GAME_START = "GAME_START",
  PLAYER_POSITION = "PLAYER_POSITION",
  PLAYER_ANIMATION = "PLAYER_ANIMATION",
  PLAYER_DATA_UPDATE = "PLAYER_DATA_UPDATE",
  PLAYER_WINNER = "PLAYER_WINNER",
  NEW_ROUND_START = "NEW_ROUND_START",

}
